title: Mohammad Sahil
logo: 1000027803.jpg
theme: jekyll-theme-minimal
description: >-
   Data Analyst | Power BI | Tableau | SQL | Excel |
  Helping businesses make data-driven decisions with clear, compelling dashboards.
